AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API using SAM
Globals:
  Function:
    Runtime: nodejs12.x
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
    MemorySize: 128
    Timeout: 5
Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: get
      CodeUri: s3://rmamchyk-sam/f80a194b4b11207b8447e9befc186515
  PostUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: post
      CodeUri: s3://rmamchyk-sam/f80a194b4b11207b8447e9befc186515
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: delete
      CodeUri: s3://rmamchyk-sam/f80a194b4b11207b8447e9befc186515
